import { createReadStream } from 'node:fs';
import { open, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { randomUUID } from 'node:crypto';
const TABLE = new Uint32Array(256);
for (let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=(c&1)?(0xedb88320^(c>>>1)):(c>>>1);TABLE[n]=c>>>0;}
function crc(state:number,bytes:Uint8Array){let c=state;for(const b of bytes)c=TABLE[(c^b)&255]^(c>>>8);return c;}
function name(v:string){return String(v||'stem.wav').replace(/[\\/:*?"<>|\u0000-\u001f]/g,'_').replace(/^\.+/,'').slice(0,180)||'stem.wav';}
function stamp(d?:Date){const x=d&&Number.isFinite(d.getTime())?d:new Date('1980-01-01T00:00:00Z');const y=Math.max(1980,x.getUTCFullYear());return{time:(x.getUTCHours()<<11)|(x.getUTCMinutes()<<5)|Math.floor(x.getUTCSeconds()/2),date:((y-1980)<<9)|((x.getUTCMonth()+1)<<5)|x.getUTCDate()};}
function u64(v:DataView,o:number,n:bigint){v.setUint32(o,Number(n&0xffffffffn),true);v.setUint32(o+4,Number((n>>32n)&0xffffffffn),true);}
export async function createStemPackageZipWriter(id:string){
 const path=join(tmpdir(),`mediacreator-stems-${id}-${randomUUID()}.zip`),file=await open(path,'w');let offset=0n,closed=false;const central:any[]=[];
 const write=async(bytes:Uint8Array)=>{let p=0;while(p<bytes.byteLength){const r=await file.write(bytes,p,bytes.byteLength-p,null);if(!r.bytesWritten)throw new Error('ZIP64 disk write stalled');p+=r.bytesWritten;}offset+=BigInt(bytes.byteLength);};
 return{path,async addFile(filename:string,sourcePath:string,modified?:Date){
  const source=await open(sourcePath,'r'),info=await source.stat(),buffer=Buffer.allocUnsafe(1048576);let state=0xffffffff;
  try{let p=0;while(p<info.size){const r=await source.read(buffer,0,Math.min(buffer.length,info.size-p),p);if(!r.bytesRead)throw new Error('ZIP64 source read stalled');state=crc(state,buffer.subarray(0,r.bytesRead));p+=r.bytesRead;}}finally{await source.close();}
  const checksum=(state^0xffffffff)>>>0,size=BigInt(info.size),encoded=new TextEncoder().encode(name(filename)),when=stamp(modified),start=offset,extra=new Uint8Array(20),ev=new DataView(extra.buffer);ev.setUint16(0,1,true);ev.setUint16(2,16,true);u64(ev,4,size);u64(ev,12,size);
  const h=new Uint8Array(30),v=new DataView(h.buffer);v.setUint32(0,0x04034b50,true);v.setUint16(4,45,true);v.setUint16(6,0x0800,true);v.setUint16(10,when.time,true);v.setUint16(12,when.date,true);v.setUint32(14,checksum,true);v.setUint32(18,0xffffffff,true);v.setUint32(22,0xffffffff,true);v.setUint16(26,encoded.length,true);v.setUint16(28,extra.length,true);await write(h);await write(encoded);await write(extra);for await(const chunk of createReadStream(sourcePath))await write(new Uint8Array(chunk));central.push({encoded,checksum,size,start,...when});
 },async close(){const centralStart=offset;for(const x of central){const extra=new Uint8Array(28),ev=new DataView(extra.buffer);ev.setUint16(0,1,true);ev.setUint16(2,24,true);u64(ev,4,x.size);u64(ev,12,x.size);u64(ev,20,x.start);const h=new Uint8Array(46),v=new DataView(h.buffer);v.setUint32(0,0x02014b50,true);v.setUint16(4,45,true);v.setUint16(6,45,true);v.setUint16(8,0x0800,true);v.setUint16(12,x.time,true);v.setUint16(14,x.date,true);v.setUint32(16,x.checksum,true);v.setUint32(20,0xffffffff,true);v.setUint32(24,0xffffffff,true);v.setUint16(28,x.encoded.length,true);v.setUint16(30,extra.length,true);v.setUint32(42,0xffffffff,true);await write(h);await write(x.encoded);await write(extra);}const centralSize=offset-centralStart,zip64Start=offset,e64=new Uint8Array(56),z=new DataView(e64.buffer);z.setUint32(0,0x06064b50,true);u64(z,4,44n);z.setUint16(12,45,true);z.setUint16(14,45,true);u64(z,24,BigInt(central.length));u64(z,32,BigInt(central.length));u64(z,40,centralSize);u64(z,48,centralStart);await write(e64);const loc=new Uint8Array(20),lv=new DataView(loc.buffer);lv.setUint32(0,0x07064b50,true);u64(lv,8,zip64Start);lv.setUint32(16,1,true);await write(loc);const end=new Uint8Array(22),e=new DataView(end.buffer);e.setUint32(0,0x06054b50,true);e.setUint16(8,0xffff,true);e.setUint16(10,0xffff,true);e.setUint32(12,0xffffffff,true);e.setUint32(16,0xffffffff,true);await write(end);await file.sync();await file.close();closed=true;return{path,size:Number(offset)};},async cleanup(){if(!closed)await file.close().catch(()=>{});closed=true;await rm(path,{force:true}).catch(()=>{});}};
}
